### ISSUE TITLE
How do i change color of the icon?

### ISSUE THREAD

**Issue by kaushikdas0** [webketje/drawio-font-awesome#1]
Thanks for this library, very helpful. How can i change the color from Black to something else?

![image](https://user-images.githubusercontent.com/13030179/80933991-9a65f380-8df8-11ea-903d-256484880244.png)

**Comment by bepuzzled** [comment]
It is possible to change your shape's colour by modifying the SVG representation of the icon. You can do so using the following steps (there may be easier ways, but they may not work in all versions of draw.io)

1. with your shape selected, right-click, "Ungroup" (may not be required in all cases; alternatively, you can click the shape twice, without double-clicking it)
2. re-select your shape right-click, "Edit Style" (or `Ctrl+e`)
3. copy the base64-encoded string that follows `image/svg+xml,` up to the semi-colon `;`:
`PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBkPSJNNDM2IDE2MGM2LjYgMCAxMi01LjQgMTItMTJ2LTQwYzAtNi42LTUuNC0xMi0xMi0xMmgtMjBWNDhjMC0yNi41LTIxLjUtNDgtNDgtNDhINDhDMjEuNSAwIDAgMjEuNSAwIDQ4djQxNmMwIDI2LjUgMjEuNSA0OCA0OCA0OGgzMjBjMjYuNSAwIDQ4LTIxLjUgNDgtNDh2LTQ4aDIwYzYuNiAwIDEyLTUuNCAxMi0xMnYtNDBjMC02LjYtNS40LTEyLTEyLTEyaC0yMHYtNjRoMjBjNi42IDAgMTItNS40IDEyLTEydi00MGMwLTYuNi01LjQtMTItMTItMTJoLTIwdi02NGgyMHptLTIyOC0zMmMzNS4zIDAgNjQgMjguNyA2NCA2NHMtMjguNyA2NC02NCA2NC02NC0yOC43LTY0LTY0IDI4LjctNjQgNjQtNjR6bTExMiAyMzYuOGMwIDEwLjYtMTAgMTkuMi0yMi40IDE5LjJIMTE4LjRDMTA2IDM4NCA5NiAzNzUuNCA5NiAzNjQuOHYtMTkuMmMwLTMxLjggMzAuMS01Ny42IDY3LjItNTcuNmg1YzEyLjMgNS4xIDI1LjcgOCAzOS44IDhzMjcuNi0yLjkgMzkuOC04aDVjMzcuMSAwIDY3LjIgMjUuOCA2Ny4yIDU3LjZ2MTkuMnoiLz48L3N2Zz4=`
4. in [CyberChef](https://gchq.github.io/CyberChef/), decode the base64-encoded string to using the `From Base64` operation
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M436 160c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20V48c0-26.5-21.5-48-48-48H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h320c26.5 0 48-21.5 48-48v-48h20c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20v-64h20c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20v-64h20zm-228-32c35.3 0 64 28.7 64 64s-28.7 64-64 64-64-28.7-64-64 28.7-64 64-64zm112 236.8c0 10.6-10 19.2-22.4 19.2H118.4C106 384 96 375.4 96 364.8v-19.2c0-31.8 30.1-57.6 67.2-57.6h5c12.3 5.1 25.7 8 39.8 8s27.6-2.9 39.8-8h5c37.1 0 67.2 25.8 67.2 57.6v19.2z"/></svg>`
5. insert `fill="red"` between `<path` and `d=` (easiest if you first copy the result from the previous operation, and paste it into the input text area of a new [CyberChef](https://gchq.github.io/CyberChef/) recipe that uses the `To Base64` operation):
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="red" d="M436 160c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20V48c0-26.5-21.5-48-48-48H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h320c26.5 0 48-21.5 48-48v-48h20c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20v-64h20c6.6 0 12-5.4 12-12v-40c0-6.6-5.4-12-12-12h-20v-64h20zm-228-32c35.3 0 64 28.7 64 64s-28.7 64-64 64-64-28.7-64-64 28.7-64 64-64zm112 236.8c0 10.6-10 19.2-22.4 19.2H118.4C106 384 96 375.4 96 364.8v-19.2c0-31.8 30.1-57.6 67.2-57.6h5c12.3 5.1 25.7 8 39.8 8s27.6-2.9 39.8-8h5c37.1 0 67.2 25.8 67.2 57.6v19.2z"/></svg>`
6. with the new SVG tag, encode into base64 using [CyberChef](https://gchq.github.io/CyberChef/) and the `To Base64` operation:
`PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBmaWxsPSJyZWQiIGQ9Ik00MzYgMTYwYzYuNiAwIDEyLTUuNCAxMi0xMnYtNDBjMC02LjYtNS40LTEyLTEyLTEyaC0yMFY0OGMwLTI2LjUtMjEuNS00OC00OC00OEg0OEMyMS41IDAgMCAyMS41IDAgNDh2NDE2YzAgMjYuNSAyMS41IDQ4IDQ4IDQ4aDMyMGMyNi41IDAgNDgtMjEuNSA0OC00OHYtNDhoMjBjNi42IDAgMTItNS40IDEyLTEydi00MGMwLTYuNi01LjQtMTItMTItMTJoLTIwdi02NGgyMGM2LjYgMCAxMi01LjQgMTItMTJ2LTQwYzAtNi42LTUuNC0xMi0xMi0xMmgtMjB2LTY0aDIwem0tMjI4LTMyYzM1LjMgMCA2NCAyOC43IDY0IDY0cy0yOC43IDY0LTY0IDY0LTY0LTI4LjctNjQtNjQgMjguNy02NCA2NC02NHptMTEyIDIzNi44YzAgMTAuNi0xMCAxOS4yLTIyLjQgMTkuMkgxMTguNEMxMDYgMzg0IDk2IDM3NS40IDk2IDM2NC44di0xOS4yYzAtMzEuOCAzMC4xLTU3LjYgNjcuMi01Ny42aDVjMTIuMyA1LjEgMjUuNyA4IDM5LjggOHMyNy42LTIuOSAzOS44LThoNWMzNy4xIDAgNjcuMiAyNS44IDY3LjIgNTcuNnYxOS4yeiIvPjwvc3ZnPg==`
7. In [draw.io](https://draw.io), use the new base64 string to replace the one in your shape's "Edit Style" dialog, et voilà. If you will be doing this often, you can create a [CyberChef](https://gchq.github.io/CyberChef/) recipe that combines three operations: `From Base64`, `Find / Replace`, and `To Base64`, in which you search for `<path` , and replace with `<path fill="red"`, which will be a bit faster. As an example, this [4-operation recipe ](https://gchq.github.io/CyberChef/#recipe=Subsection('.*,(%5B%5E;%5D%2B);.*',true,true,false)From_Base64('A-Za-z0-9%2B/%3D',true)Find_/_Replace(%7B'option':'Regex','string':'%3Cpath'%7D,'%3Cpath%20fill%3D%22red%22',true,false,true,false)To_Base64('A-Za-z0-9%2B/%3D')&input='') processes the entire output from the `Edit Style` dialog, and turns it red, without having to extract the base64-encoded string.

**Comment by webketje** [comment]
@bepuzzled I read that too and found it way too cumbersome.
@kaushikdas0 Unfortunately it is not possible to pass values from draw.io's fill/stroke/font color or other options to svg icons. What I can do, is generate *all* the icons in a specific color. Would that help you?

**Comment by webketje** [comment]
Actually I just pushed an update with differently colored versions.
I'm closing this issue as this is the most I can do, thank you for your participation!
