### ISSUE TITLE
[Desktop 16.1.2] Can only import unzipped library via "File > New Library..."

### ISSUE THREAD

**Issue by tsouchlarakis** [webketje/drawio-font-awesome#2]
The flow outlined in the README doesn't appear to work on draw.io Desktop 16.1.2:

1. File
2. Open library...
3. Select unzipped folder

The above doesn't work because the file select dialog doesn't recognize the Font Awesome document files:

<img width="712" alt="Screen Shot 2022-01-15 at 7 33 07 PM" src="https://user-images.githubusercontent.com/26070649/149643901-bf4cd32a-e1b7-4ffc-af13-39d332f1ab97.png">

Instead, I was able to import the Font Awesome library by the following:

1. File
2. New library...
3. Import
4. Select all Font Awesome document files
5. Save

<img width="721" alt="Screen Shot 2022-01-15 at 7 34 09 PM" src="https://user-images.githubusercontent.com/26070649/149643919-3254aab0-507c-4275-9bc8-c9d693e2e3ec.png">

**Comment by tsouchlarakis** [comment]
Note that the File > Open library... flow works just fine if the user navigates to the outputted .xml file after step (5) above.

**Comment by webketje** [comment]
@tsouchlarakis this looks like an *allowed filetypes* issue. Could you try renaming 1 file to `FontAwesome.xml` and try again? If this works, I'll make sure to output `.xml` files in the following dists

**Comment by tsouchlarakis** [comment]
@webketje yep, renaming `FontAwesome` (no extension, downloaded from [here](https://cdn.jsdelivr.net/gh/webketje/drawio-font-awesome@online/FontAwesome)) to `FontAwesome.xml`, then loading via File > Open library... works perfectly.

**Comment by tsouchlarakis** [comment]
One small caveat is that if the file is renamed _after_ selecting File > Open library... (i.e. the file select dialog has already been opened), then it still appears gray. So the working flow would be:

1. User downloads FontAwesome file from the above link
2. User renames file to `FontAwesome.xml`
3. File > Open library...

**Comment by webketje** [comment]
That's not a workable solution.. I think if it is distributed with `.xml` it will also appear as the library name in Drawio, which is not desirable. I'll have to test it on Windows & see what the behavior is there

**Comment by webketje** [comment]
I've added a note to the desktop install instructions. Tested on Linux with latest Draw.io desktop, it does show up after changing file type in the file open dialog from "drawio diagrams" to "All Files".

**Comment by webketje** [comment]
I believe this issue has been addressed with: 16dca4952308196afb896c59c4a3f9b6e4169352
