### ISSUE TITLE
Allow icons to appear in Mermaid diagrams in Draw.IO

### ISSUE THREAD

**Issue by matthewroweoptimal** [webketje/drawio-font-awesome#4]
Is there a syntax for referencing these icons in Mermaid diagram markdown, or is it an omission in the draw.IO renderer that prevents them appearing?

Issue flagged on the draw.io dev.
https://github.com/jgraph/drawio/issues/3893

**Comment by webketje** [comment]
Sorry I missed this, and I don't think this is possible (for one, the icon identifiers are different). diagrams.net does not support rendering icon fonts and the icons in this library are converted to base64-encoded image data URLs as soon as they are dragged into a canvas

Including the icons in a Mermaid diagram imported to draw.io is definitely beyond the scope of what I had imagined for this library.
I'm afraid you will need to replace the icon names with the matching icons from this lib.
